spec:
  functions:
  - url: ./get_data.py
    name: get-data
    kind: job
    image: mlrun/mlrun
  - url: ./train_model.py
    name: train-model
    kind: job
    image: mlrun/mlrun
  - url: ./deploy_model.py
    name: deploy-model
    kind: job
    image: mlrun/mlrun
  conda: ''
  desired_state: online
  source: ''
  workflows:
  - path: training_pipeline.py
    name: train
metadata:
  name: iguazio-academy
kind: project
